name: template
description: Flutter boilerplate project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

  provider: ^6.1.5
  dart_json_mapper: ^2.2.16
  property_change_notifier: ^0.5.0

  intl: 0.20.2
  hive_flutter: 1.1.0

  retrofit: ^4.0.1
  logger: any
  dio: ^5.8.0+1
  dio_http2_adapter: ^2.6.0
  jwt_decode: 0.3.1

  auto_route: ^10.0.0
  reflectable: ^4.0.13
  flutter_flavor: ^3.1.4

  pub_semver: ^2.1.0

  permission_handler: ^12.0.0+1
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  platform_device_id: 1.0.1
  get_mac_address: 0.0.2

  fluttertoast: ^8.2.12
  adaptive_dialog: ^2.4.2
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  animate_do: ^4.2.0
  avatar_glow: ^3.0.1

  firebase_core: ^3.15.0
  firebase_analytics: ^11.5.1
  firebase_crashlytics: ^4.3.8
  firebase_messaging: ^15.2.8
  flutter_local_notifications: ^19.3.0
  firebase_remote_config: ^5.4.6
  launch_review: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  auto_route_generator: ^10.0.0
  flutter_lints: ^6.0.0



  retrofit_generator:
    path: retrofit_generator/

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: display-regular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf

    - family: rounded-black
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf

    - family: rounded-bold
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf

    - family: rounded-heavy
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf

    - family: rounded-medium
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf

    - family: rounded-regular
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf

    - family: rounded-semiBold
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf

    - family: text-bold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf