name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/
version: 8.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.8.0
  build: ^2.4.0
  built_collection: ^5.1.1
  code_builder: ^4.5.0
  dart_style: ^3.0.0
  dio: ^5.1.0
  retrofit: ^4.1.0
  source_gen: ^2.0.0
  tuple: ^2.0.1

dev_dependencies:
  lints: ^6.0.0
  source_gen_test: ^1.0.4
  test: ^1.24.0